# Generated by Django 4.0 on 2022-09-04 03:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account_module', '0001_initial'),
        ('product_module', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد ')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='زمان ویرایش ')),
                ('paid', models.BooleanField(default=False, verbose_name='   پردخت شده ؟ ')),
                ('is_in_order', models.BooleanField(default=False, verbose_name=' موجود در سفارش ؟')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='account_module.user', verbose_name='خریدار')),
            ],
            options={
                'verbose_name': 'سبد خرید',
                'verbose_name_plural': 'سبد خرید',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='قیمت واحد ')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='تعداد محصول')),
                ('cart', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='cart_module.cart', verbose_name='شناسه سبد خرید')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='product_module.product', verbose_name='شناسه محصول')),
            ],
            options={
                'verbose_name': 'جزییات سبد خرید',
                'verbose_name_plural': 'جزییات سبد خرید',
            },
        ),
    ]
